$(document).ready(function(){
	$("#default").show();
	$("#hex1-data").hide();
	$("#hex2-data").hide();
	$("#hex3-data").hide();
	$("#hex4-data").hide();
	$("#hex5-data").hide();
	$("#hex6-data").hide();
	$("#hex7-data").hide();

	$("#hex1").mouseover(function(){
		$("#default").hide();
		$("#hex1-data").show();
		$("#hex2-data").hide();
		$("#hex3-data").hide();
		$("#hex4-data").hide();
		$("#hex5-data").hide();
		$("#hex6-data").hide();
		$("#hex7-data").hide();
	});
	$("#hex2").mouseover(function(){
		$("#default").hide();
		$("#hex1-data").hide();
		$("#hex2-data").show();
		$("#hex3-data").hide();
		$("#hex4-data").hide();
		$("#hex5-data").hide();
		$("#hex6-data").hide();
		$("#hex7-data").hide();
	});
	$("#hex3").mouseover(function(){
		$("#default").hide();
		$("#hex1-data").hide();
		$("#hex2-data").hide();
		$("#hex3-data").show();
		$("#hex4-data").hide();
		$("#hex5-data").hide();
		$("#hex6-data").hide();
		$("#hex7-data").hide();
	});
	$("#hex4").mouseover(function(){
		$("#default").hide();
		$("#hex1-data").hide();
		$("#hex2-data").hide();
		$("#hex3-data").hide();
		$("#hex4-data").show();
		$("#hex5-data").hide();
		$("#hex6-data").hide();
		$("#hex7-data").hide();
	});
	$("#hex5").mouseover(function(){
		$("#default").hide();
		$("#hex1-data").hide();
		$("#hex2-data").hide();
		$("#hex3-data").hide();
		$("#hex4-data").hide();
		$("#hex5-data").show();
		$("#hex6-data").hide();
		$("#hex7-data").hide();
	});
	$("#hex6").mouseover(function(){
		$("#default").hide();
		$("#hex1-data").hide();
		$("#hex2-data").hide();
		$("#hex3-data").hide();
		$("#hex4-data").hide();
		$("#hex5-data").hide();
		$("#hex6-data").show();
		$("#hex7-data").hide();
	});
	$("#hex7").mouseover(function(){
		$("#default").hide();
		$("#hex1-data").hide();
		$("#hex2-data").hide();
		$("#hex3-data").hide();
		$("#hex4-data").hide();
		$("#hex5-data").hide();
		$("#hex6-data").hide();
		$("#hex7-data").show();
	});

});